---
title: "ARM_TextMining"
author: "Sreevani Basvaraj Patil"
date: "2023-03-05"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#install.packages("tcltk")
library(tidyverse)
library(dplyr)
library(gridExtra)
library(webr)
library(repr)
library(ggplot2)
library(plotly)
library(arules)
library(tokenizers)
library(stopwords)
#library(tcltk)
library(arulesViz) ## load last
```


```{r}
df <- read.csv("/Users/sbp/Downloads/cleaned_csv.csv")

corpus <- df$ctext_

```
```{r}
#read the data
tf <- "/Users/sbp/Downloads/trans.csv"
trans <- file(tf)
tokens <- tokenizers::tokenize_words(corpus[1], stopwords = stopwords::stopwords("en"), lowercase = TRUE, strip_punct = TRUE, strip_numeric = TRUE, simplify = TRUE)
cat(unlist(str_squish(tokens)), "\n", file = trans, sep = ",")
close(trans)

```
```{r}
trans <- file(tf, open = "a")
for(i in 2:nrow(df)){
  tokens <- tokenizers::tokenize_words(df$ctext[i], stopwords = stopwords::stopwords("en"), lowercase = TRUE, strip_punct = TRUE, strip_numeric = TRUE, simplify = TRUE)
  cat(unlist(str_squish(tokens)), "\n", file = trans, sep = ",")
}
close(trans)
```

```{r}
TweetTrans <- read.transactions(tf,
                                rm.duplicates = FALSE,
                                format = "basket",
                                sep = ",")
inspect(head(TweetTrans))
sample_trans <- sample(TweetTrans, 50)
summary(sample_trans)
```

```{r}
TweetDf <- read.transactions(tf, header = FALSE, sep = ",")
#inspect(TweetDf)
```

```{r}
TweetTrans_rules <- arules::apriori(TweetDf,
                                    parameter = list(support = 0.2, confidence = 0.08))

inspect(TweetTrans_rules)
```

```{r}
TweetTrans_rules <- arules::apriori(TweetDf,
                                    parameter = list(support = 0.5, confidence = 0.1),appearance = list (default="lhs",lhs="movie"))

inspect(TweetTrans_rules)
```
```
```{r}
SortedRules_sup <- sort(TweetTrans_rules, by = "lift", decreasing = TRUE)
inspect(SortedRules_sup)
```
```{r}
rules_conf <- sort (TweetTrans_rules, by="lift", decreasing=TRUE) # 'high-confidence' rules.
```

```{r}
plot(SortedRules_sup,method = "graph")
```
```{r}
plot(SortedRules_sup[1:50], measure = "confidence")

```
```{r}

plot(SortedRules_sup[1:15], method="graph")
```
```{r}
plot(SortedRules_sup[1:30], method="paracoord")
```

```{r}
```